### ISSUE TITLE
Unreadble on NPC page

### ISSUE THREAD

**Issue by Terrribad** [posimagi/bg-wiki-dark-mode#16]
https://www.bg-wiki.com/ffxi/Balasiel

Grey font on white background, have to highlight words to be able to read them

**Comment by posimagi** [comment]
Thanks for the report.

Header style:
```css
    background-color: #E2E1E1;
    color: #000000;
```
Body style:
```css
    background-color: #EFEEEE; 
```

I will fix the styles tonight, there's a CSS change so they will take 4-24 hours to be updated.

**Comment by posimagi** [comment]
The fix has been added. It should be legible once it works through the cache.

**Comment by posimagi** [comment]
Added some additional CSS to this that should make the table body render better.

**Comment by posimagi** [comment]
Still some strangeness to work out here, I will take another look at it tomorrow.

**Comment by posimagi** [comment]
I think the NPC template is going to need to be reworked, the fixes for related templates (Zone Quest and Zone Map) didn't help the NPC template.

**Comment by posimagi** [comment]
A temporary fix has been implemented for this issue. Long-term fix will come later once higher-priority tasks are done.

![image](https://user-images.githubusercontent.com/1747598/231051484-64f6694e-ad16-450a-8bc3-50c719014216.png)
