### ISSUE TITLE
Sinister Reign page tons of light elements in Dark Mode

### ISSUE THREAD

**Issue by ithorien** [posimagi/bg-wiki-dark-mode#19]
![2023-04-18 10 57 50](https://user-images.githubusercontent.com/4006255/232834859-830566bf-6b4f-406b-9c38-8afb35e5fd8e.png)

Looks like most tables on the page are light, this is potentially an overlap with other page issues.

**Comment by posimagi** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/1747598/232882689-d3233362-c9fc-4cfe-a7ef-99265fcc2e27.png)

**Comment by ithorien** [comment]
Amazing work! Hope you don't mind me asking through this way, but I'm pretty frequent on wiki right now, but I don't want to presume and start submitting literally every issue I see without asking; so here's me asking I suppose, would you like most of those submitted?

**Comment by posimagi** [comment]
Go for it. Even issues I'm aware of it's still valuable to have a paper trail for. There's going to be a very long tail of pages that don't use standard side-wide templates that will have to be dealt with individually.
