### ISSUE TITLE
Some/more KI pages need small adjustments

### ISSUE THREAD

**Issue by ithorien** [posimagi/bg-wiki-dark-mode#20]
Haven't gone ham, but it seems to affect all KI pages-

![2023-04-20 15 46 33](https://user-images.githubusercontent.com/4006255/233483971-1056a1c7-1faf-42a6-8952-86046f1d1cdc.png)

TYTY! <3<3

**Comment by posimagi** [comment]
I have put in the CSS changes to fix this, need to wait for them to propagate through the cache before making the wikitext changes to apply the CSS.

**Comment by posimagi** [comment]
The following edit to `Template:Key Item Header` does not quite solve the issue. There is an outstanding CSS bug that needs to be addressed first.

```
<includeonly>{{#if: {{{Type|}}} | [[Category:{{{Type}}}]] | [[Category:{{{type}}}]] }}
__NOTOC__

{{#if: {{{Image|}}}|[[Image:{{{Image}}}|{{PAGENAME}}]]|[[Image:{{PAGENAME}}.jpg|{{PAGENAME}}]]}}
{{#if: {{{Image|}}}|{{#ifexist: Image:{{{Image}}}||[[Category:Need Key Item Image]]}}|{{#ifexist: Image:{{PAGENAME}}.jpg||[[Category:Need Key Item Image]]}}}}</includeonly>
{| class="BorderlessStandard keyitem" style="width: 100%; max-width: 788px; text-align: center;"
|-
! colspan="100%" height="34px" | 
{| style="width: 100%;" |
| style="width: 100%; text-align: center; padding 3px; background: #4b4d4f; color: #eeeeee;" | [[File:Key Item.png|link=]] Key Item Description <div style="float: right;">[[Image:{{BG_icon}} | link=:Special:WhatLinksHere/{{PAGENAME}} | Pages on this wiki that reference this item]]</div>
|}
|-
! colspan="100%" style="background: #9e9dff;" height=2px|
|-
! width="34%" | Type
! width="66%" | Description 
|-
| {{#if: {{{Type|}}} | [[:Category:{{{Type}}}{{!}}{{{Type}}}]] | [[:Category:{{{type}}}{{!}}{{{type}}}]] }}
| {{#if: {{{Description|}}} | {{{Description}}} | {{{description}}} }}
|-
|}<includeonly>[[Category:Key Items]]</includeonly>
<noinclude>[[Category:Templates/ItemPages|{{PAGENAME}}]]</noinclude>

```

**Comment by posimagi** [comment]
I'm still not sure why I can't get this one working correctly, it's currently the highest priority.

**Comment by posimagi** [comment]
Finally fixed the first table, which was the most egregious one. It had a pathological layout with embedded tables, now fixed. The others should be easier.

**Comment by posimagi** [comment]
Done! 

<img width="815" alt="image" src="https://github.com/posimagi/bg-wiki-dark-mode/assets/1747598/ee42f388-ca2d-40e9-b85a-0dc3fd0eb573">
