### ISSUE TITLE
Magian trials

### ISSUE THREAD

**Issue by ithorien** [posimagi/bg-wiki-dark-mode#21]
Bit of a domino, seems to affect a bunch of trial pages, mostly at weapon root page level-
![2023-04-20 15 47 49](https://user-images.githubusercontent.com/4006255/233484567-d36b2dcd-4796-43e6-bf71-ee24466edaaa.png)

TYTY! <3<3

**Comment by posimagi** [comment]
I'm aware of this one, it's not going to be an easy fix but I might be able to create a temporary solution until we can rework the tables.

**Comment by posimagi** [comment]
Light mode CSS:
```
table.magiantrials {
	background: #000878;
}
table.magiantrials th {
	background: #ADBDCC;
}
table.magiantrials tr {
	background: #dfe4ff;
}
```

**Comment by posimagi** [comment]
Wikitext fix:
- Add class `magiantrials` to table
- Remove all instances of `background`, `background-color`, and `BGCOLOR` from tables

**Comment by posimagi** [comment]
Dark mode CSS:
```
table.magiantrials {
	background: #000878;
}
table.magiantrials th {
	background: #334352;
}
table.magiantrials tr {
	background: var(--background-color);
}
```

**Comment by posimagi** [comment]
Fixed for all category pages.
