### ISSUE TITLE
Minor file detail table issue

### ISSUE THREAD

**Issue by ithorien** [posimagi/bg-wiki-dark-mode#22]
This one looks to be minor, some detail table headers are in need of some love-
![2023-04-20 15 50 23](https://user-images.githubusercontent.com/4006255/233484808-8bb7cfd6-af9d-46bf-8886-02210c8d68ae.png)

TYTY!<3<3

**Comment by posimagi** [comment]
I'll take a look, not sure offhand whether or not this will be easy, a few of the things that are built in to MediaWiki (rather than tables we define) have proven challenging.

**Comment by posimagi** [comment]
At the moment I can't reproduce this issue, it may be related to the other OOUI-related bugs on special pages and in the wikitext editor. Putting this on the back burner for now at least until #10 is fixed.

**Comment by posimagi** [comment]
As far as I can tell this was fixed by fixing #10. There are still some other minor metadata issues but I'm not sure how to fix them and they are out of the way.
