### ISSUE TITLE
Zone page random tables need fixing

### ISSUE THREAD

**Issue by ithorien** [posimagi/bg-wiki-dark-mode#24]
Looks like random, possibly depending on template when created; there are random tables that need flipping-
![2023-04-20 15 51 59](https://user-images.githubusercontent.com/4006255/233486021-4deb57bc-7a99-4b91-84ae-4ed6a094e7ea.png)

TYTY!<3<3

**Comment by posimagi** [comment]
Should be a relatively easy fix.

**Comment by posimagi** [comment]
Fixed.
