### ISSUE TITLE
Coalition page

### ISSUE THREAD

**Issue by ithorien** [posimagi/bg-wiki-dark-mode#26]
Main tables need some flippage-
![2023-04-24 07 51 26](https://user-images.githubusercontent.com/4006255/234001591-efa6dfe5-0364-48b7-bfaa-86c799dbe775.png)
TYTY!<3<3

**Comment by posimagi** [comment]
The good news is this is a pure wikitext fix. The bad news is I'm out of town and I really need my desktop PC tools for this one, so it won't get done this week. The other good news, though, is that this is one of those changes that should significantly reduce the size of the page (and improve loading speed) as a side effect.

**Comment by ithorien** [comment]
Nice, and maybe if it's the same wikitext fix it'll have the same positive side effect on others? 🤞

**Comment by posimagi** [comment]
Fixed.
