### ISSUE TITLE
Mission/mission quest pages

### ISSUE THREAD

**Issue by ithorien** [posimagi/bg-wiki-dark-mode#27]
Looks like most of these aside from Voracious need some help-
![2023-04-24 07 52 31](https://user-images.githubusercontent.com/4006255/234002131-74ce7a57-33ed-409f-beca-73d5d94470d8.png)
![2023-04-24 07 52 56](https://user-images.githubusercontent.com/4006255/234002161-fef5f4d4-a5b0-4ff8-bd59-43ca6b964741.png)
![2023-04-24 07 53 19](https://user-images.githubusercontent.com/4006255/234002188-f6b3d4c6-d724-40ba-a9e9-8d2d3a49558b.png)
TYTY!<3<3

**Comment by posimagi** [comment]
I've implemented a stopgap measure to make these legible. Long-term I will want to make some specialized CSS to make these prettier in dark mode, but going to close this ticket for now to focus on stuff that's illegible first.
