### ISSUE TITLE
Oboro page

### ISSUE THREAD

**Issue by ithorien** [posimagi/bg-wiki-dark-mode#28]
Few tables on page need some help-
![2023-04-24 08 13 21](https://user-images.githubusercontent.com/4006255/234007074-f71b6f1d-9b4d-4fbc-990e-b94cba3867a2.png)
![2023-04-24 08 13 27](https://user-images.githubusercontent.com/4006255/234007087-e74c86d8-78bd-4cb7-83e3-2756a3ab449b.png)
TYTY!<3<3

**Comment by posimagi** [comment]
Added a stopgap measure. Longer-term there's more I can do to make it look better, but it's legible for now.
